[2025-03-20T13:00:30.232+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T13:00:30.297+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_breweries_list.clean_data manual__2025-03-20T12:58:15.706666+00:00 [queued]>
[2025-03-20T13:00:30.350+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_breweries_list.clean_data manual__2025-03-20T12:58:15.706666+00:00 [queued]>
[2025-03-20T13:00:30.354+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-20T13:00:30.454+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): clean_data> on 2025-03-20 12:58:15.706666+00:00
[2025-03-20T13:00:30.478+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-20T13:00:30.484+0000] {standard_task_runner.py:72} INFO - Started process 162 to run task
[2025-03-20T13:00:30.513+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_breweries_list', 'clean_data', 'manual__2025-03-20T12:58:15.706666+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/breweries_list_etl.py', '--cfg-path', '/tmp/tmpsxrniont']
[2025-03-20T13:00:30.538+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask clean_data
[2025-03-20T13:00:30.754+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_breweries_list.clean_data manual__2025-03-20T12:58:15.706666+00:00 [running]> on host 155a81680138
[2025-03-20T13:00:31.008+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_breweries_list' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T12:58:15.706666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T12:58:15.706666+00:00'
[2025-03-20T13:00:31.010+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-20T13:00:31.011+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-20T13:00:31.011+0000] {logging_mixin.py:190} INFO - Current task name:clean_data state:running start_date:2025-03-20 13:00:30.298872+00:00
[2025-03-20T13:00:31.012+0000] {logging_mixin.py:190} INFO - Dag name:ETL_breweries_list and current dag run status:running
[2025-03-20T13:00:31.012+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T13:00:31.047+0000] {base.py:84} INFO - Retrieving connection 'my_spark_conn'
[2025-03-20T13:00:31.050+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /***/scripts/fetch_and_clean_data.py
[2025-03-20T13:01:09.934+0000] {spark_submit.py:645} INFO - Using properties file: null
[2025-03-20T13:01:10.380+0000] {spark_submit.py:645} INFO - Parsed arguments:
[2025-03-20T13:01:10.381+0000] {spark_submit.py:645} INFO - master                  spark://spark-master:7077
[2025-03-20T13:01:10.382+0000] {spark_submit.py:645} INFO - remote                  null
[2025-03-20T13:01:10.383+0000] {spark_submit.py:645} INFO - deployMode              client
[2025-03-20T13:01:10.384+0000] {spark_submit.py:645} INFO - executorMemory          null
[2025-03-20T13:01:10.385+0000] {spark_submit.py:645} INFO - executorCores           null
[2025-03-20T13:01:10.385+0000] {spark_submit.py:645} INFO - totalExecutorCores      null
[2025-03-20T13:01:10.386+0000] {spark_submit.py:645} INFO - propertiesFile          null
[2025-03-20T13:01:10.386+0000] {spark_submit.py:645} INFO - driverMemory            null
[2025-03-20T13:01:10.387+0000] {spark_submit.py:645} INFO - driverCores             null
[2025-03-20T13:01:10.388+0000] {spark_submit.py:645} INFO - driverExtraClassPath    null
[2025-03-20T13:01:10.389+0000] {spark_submit.py:645} INFO - driverExtraLibraryPath  null
[2025-03-20T13:01:10.389+0000] {spark_submit.py:645} INFO - driverExtraJavaOptions  null
[2025-03-20T13:01:10.389+0000] {spark_submit.py:645} INFO - supervise               false
[2025-03-20T13:01:10.390+0000] {spark_submit.py:645} INFO - queue                   null
[2025-03-20T13:01:10.390+0000] {spark_submit.py:645} INFO - numExecutors            null
[2025-03-20T13:01:10.391+0000] {spark_submit.py:645} INFO - files                   null
[2025-03-20T13:01:10.391+0000] {spark_submit.py:645} INFO - pyFiles                 null
[2025-03-20T13:01:10.392+0000] {spark_submit.py:645} INFO - archives                null
[2025-03-20T13:01:10.392+0000] {spark_submit.py:645} INFO - mainClass               null
[2025-03-20T13:01:10.393+0000] {spark_submit.py:645} INFO - primaryResource         file:/***/scripts/fetch_and_clean_data.py
[2025-03-20T13:01:10.393+0000] {spark_submit.py:645} INFO - name                    arrow-spark
[2025-03-20T13:01:10.414+0000] {spark_submit.py:645} INFO - childArgs               []
[2025-03-20T13:01:10.415+0000] {spark_submit.py:645} INFO - jars                    null
[2025-03-20T13:01:10.415+0000] {spark_submit.py:645} INFO - packages                null
[2025-03-20T13:01:10.416+0000] {spark_submit.py:645} INFO - packagesExclusions      null
[2025-03-20T13:01:10.417+0000] {spark_submit.py:645} INFO - repositories            null
[2025-03-20T13:01:10.417+0000] {spark_submit.py:645} INFO - verbose                 true
[2025-03-20T13:01:10.418+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:10.418+0000] {spark_submit.py:645} INFO - Spark properties used, including those specified through
[2025-03-20T13:01:10.419+0000] {spark_submit.py:645} INFO - --conf and those from the properties file null:
[2025-03-20T13:01:10.419+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:10.419+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:10.420+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:13.645+0000] {spark_submit.py:645} INFO - Main class:
[2025-03-20T13:01:13.651+0000] {spark_submit.py:645} INFO - org.apache.spark.deploy.PythonRunner
[2025-03-20T13:01:13.673+0000] {spark_submit.py:645} INFO - Arguments:
[2025-03-20T13:01:13.674+0000] {spark_submit.py:645} INFO - file:/***/scripts/fetch_and_clean_data.py
[2025-03-20T13:01:13.675+0000] {spark_submit.py:645} INFO - null
[2025-03-20T13:01:13.677+0000] {spark_submit.py:645} INFO - Spark config:
[2025-03-20T13:01:13.678+0000] {spark_submit.py:645} INFO - (spark.app.name,arrow-spark)
[2025-03-20T13:01:13.679+0000] {spark_submit.py:645} INFO - (spark.app.submitTime,1742475673542)
[2025-03-20T13:01:13.680+0000] {spark_submit.py:645} INFO - (spark.master,spark://spark-master:7077)
[2025-03-20T13:01:13.680+0000] {spark_submit.py:645} INFO - (spark.submit.deployMode,client)
[2025-03-20T13:01:13.681+0000] {spark_submit.py:645} INFO - (spark.submit.pyFiles,)
[2025-03-20T13:01:13.683+0000] {spark_submit.py:645} INFO - Classpath elements:
[2025-03-20T13:01:13.713+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:13.730+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:13.734+0000] {spark_submit.py:645} INFO - 
[2025-03-20T13:01:14.535+0000] {spark_submit.py:645} INFO - python3: can't open file '/***/scripts/fetch_and_clean_data.py': [Errno 2] No such file or directory
[2025-03-20T13:01:14.593+0000] {spark_submit.py:645} INFO - 25/03/20 13:01:14 INFO ShutdownHookManager: Shutdown hook called
[2025-03-20T13:01:14.600+0000] {spark_submit.py:645} INFO - 25/03/20 13:01:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-c197effc-2633-4b46-8973-57d402286f17
[2025-03-20T13:01:14.750+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /***/scripts/fetch_and_clean_data.py. Error code is: 2.
[2025-03-20T13:01:14.800+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-20T13:01:14.801+0000] {logging_mixin.py:190} INFO - Task start:2025-03-20 13:00:30.298872+00:00 end:2025-03-20 13:01:14.799706+00:00 duration:44.500834
[2025-03-20T13:01:14.802+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): clean_data> dag:<DAG: ETL_breweries_list> dagrun:<DagRun ETL_breweries_list @ 2025-03-20 12:58:15.706666+00:00: manual__2025-03-20T12:58:15.706666+00:00, state:running, queued_at: 2025-03-20 12:58:15.764201+00:00. externally triggered: True>
[2025-03-20T13:01:14.803+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /***/scripts/fetch_and_clean_data.py. Error code is: 2.
[2025-03-20T13:01:14.805+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ETL_breweries_list, task_id=clean_data, run_id=manual__2025-03-20T12:58:15.706666+00:00, execution_date=20250320T125815, start_date=20250320T130030, end_date=20250320T130114
[2025-03-20T13:01:14.963+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T13:01:14.965+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 142 for task clean_data (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /***/scripts/fetch_and_clean_data.py. Error code is: 2.; 162)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /***/scripts/fetch_and_clean_data.py. Error code is: 2.
[2025-03-20T13:01:15.035+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-20T13:01:15.094+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T13:01:15.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
